<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="robot_properties.xacro" />
    <xacro:include filename="component_macros.xacro" />
    <xacro:include filename="sensor_macros.xacro" />

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="blue">
        <color rgba="0 0 1 1" />
    </material>

    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <material name="green">
        <color rgba="0 1 0 1" />
    </material>

    <material name="red">
        <color rgba="1 0 0 1" />
    </material>

    <!-- BASE LINK OBJECT -->

    <link name="base_link">
    </link>

    <!-- CHASSIS OBJECT -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="-${chassis_length/2} 0.0 0.0" />
    </joint>

    <xacro:chassis
        length="${chassis_length}"
        width="${chassis_width}"
        height="${chassis_height}"
        mass="${chassis_mass}"
    />

    <!-- WHEELS -->
    <!-- Front Left Wheel -->
    <xacro:wheel
        robot_pos="front_left"
        radius="${wheel_radius}"
        width="${wheel_width}"
        mass="${wheel_mass}"
    />

    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel" />
        <axis xyz="0.0 0.0 1" />
        <origin
            xyz="${wheel_base/2} ${track_width/2} ${wheel_z_offset}"
            rpy="-${pi/2} 0.0 0.0"
        />
    </joint>

    <!-- Front Right Wheel -->
    <xacro:wheel
        robot_pos="front_right"
        radius="${wheel_radius}"
        width="${wheel_width}"
        mass="${wheel_mass}"
    />

    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel" />
        <axis xyz="0.0 0.0 -1" />
        <origin
            xyz="${wheel_base/2} -${track_width/2} ${wheel_z_offset}"
            rpy="${pi/2} 0.0 0.0"
        />
    </joint>

    <!-- Back Left Wheel -->
    <xacro:wheel
        robot_pos="back_left"
        radius="${wheel_radius}"
        width="${wheel_width}"
        mass="${wheel_mass}"
    />

    <joint name="back_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_left_wheel" />
        <axis xyz="0.0 0.0 1" />
        <origin
            xyz="-${wheel_base/2} ${track_width/2} ${wheel_z_offset}"
            rpy="-${pi/2} 0.0 0.0"
        />
    </joint>

    <!-- Back Right Wheel -->
    <xacro:wheel
        robot_pos="back_right"
        radius="${wheel_radius}"
        width="${wheel_width}"
        mass="${wheel_mass}"
    />

    <joint name="back_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_right_wheel" />
        <axis xyz="0.0 0.0 -1" />
        <origin
            xyz="-${wheel_base/2} -${track_width/2} ${wheel_z_offset}"
            rpy="${pi/2} 0.0 0.0"
        />
    </joint>

    <!-- Front webcam -->
    <xacro:webcam
        name="front_webcam"
    />

    <joint name="front_webcam_joint" type="fixed">
        <parent link="chassis" />
        <child link="front_webcam_link" />
        <origin xyz="${webcam_x_offset} ${webcam_y_offset} ${webcam_z_offset}" rpy="0 0 0" />
    </joint>
</robot>