<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="chassis_length" value="1.0" />
    <xacro:property name="chassis_width" value="0.5" />
    <xacro:property name="chassis_height" value="0.5" />
    <xacro:property name="chassis_mass" value="1.0" />

    <xacro:property name="wheel_radius" value="0.25" />
    <xacro:property name="wheel_width" value="0.1" />
    <xacro:property name="wheel_mass" value="1.0" />

    <xacro:property name="track_width" value="${chassis_width + wheel_width}" />
    <xacro:property name="wheel_base" value=".6" />
    <xacro:property name="wheel_z_offset" value="0.1" />

    <xacro:property name="webcam_x_offset" value="${chassis_length}" />
    <xacro:property name="webcam_y_offset" value="0.0" />
    <xacro:property name="webcam_z_offset" value="${chassis_height}" />

</robot>