<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="robot_properties.xacro" />

    <joint name="camera_joint" type="fixed">
        <parent link="chassis"/>
        <child link="camera_link"/>
        <origin xyz="${chassis_length} 0 ${chassis_height + 0.015}" rpy="0 0 0"/>
    </joint>
    
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.03 0.1 0.03"/>
            </geometry>
            <material name='red'/>
        </visual>
    </link>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="camera_link_optical"></link>

    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        <sensor name="camera" type="depth">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
                <horizonal_fov>1.134</horizonal_fov>
                <image>
                    <format>B8G8R8</format>
                    <width>1280</width>
                    <height>720</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
                <min_depth>0.1</min_depth>
                <max_depth>100</max_depth>
            </plugin>
        </sensor>
    </gazebo>

</robot>