<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="chassis_length" value="1.065" />
    <xacro:property name="chassis_width" value="0.365" />
    <xacro:property name="chassis_height" value="0.365" />
    <xacro:property name="chassis_mass" value="20.0" />

    <xacro:property name="wheel_radius" value="0.1975" />
    <xacro:property name="wheel_width" value="0.070" />
    <xacro:property name="wheel_mass" value="2.44" />

    <xacro:property name="track_width" value="${chassis_width + wheel_width}" />
    <xacro:property name="wheel_base" value="0.597" />
    <xacro:property name="wheel_z_offset" value="0.098" />
</robot>